version: '3.8'

services:
  databasePg:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=encuentros_deportivos2P
      - POSTGRES_USER=Xavier
    ports:
      - '5432:5432'
