version: "3"

services:
  equipos:
    build: ./Equipos-service
    depends_on:
      - mongoequipos
    environment:
      - MONGODB_URI=mongodb://mongoequipos:27017/Equiposbd

  mongoequipos:
    container_name: mongoEquipos
    image: mongo
    ports:
      - "27017:27017"

  torneos:
    build: ./Torneos-service
    depends_on:
      - mongotorneos
    environment:
      - MONGODB_URL=mongodb://mongotorneos:27017/torneosdb

  mongotorneos:
    container_name: mongoTorneos
    image: mongo
    ports:
      - "27018:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - equipos
      - torneos
