version: "3"

services:
  equipos:
    build: ./Microservicios-express/Servicio-Equipos
    depends_on:
      - mongoequipos
    environment:
      - MONGODB_URI=mongodb://mongoequipos:27017/Equiposbd

  mongoequipos:
    container_name: mongoEquipos
    image: mongo
    ports:
      - "27017:27017"

  torneos:
    build: ./Microservicios-express/Servicio-Torneos
    depends_on:
      - mongotorneos
    environment:
      - MONGODB_URL=mongodb://mongotorneos:27017/torneosdb

  mongotorneos:
    container_name: mongoTorneos
    image: mongo
    ports:
      - "27018:27017"

  partidos:
    build: ./Microservicios-express/Servicio-Partidos
    depends_on:
      - mongopartidos
    environment:
      - MONGODB_URLL=mongodb://mongopartidos:27017/partidosdb

  mongopartidos:
    container_name: mongoPartidos
    image: mongo
    ports:
      - "27019:27017"

  monolitico:
    build: ./monolithic-nest
    depends_on:
      - databasePg
    ports:
      - "443:443"

  databasePg:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=encuentros_deportivos2P
      - POSTGRES_USER=Xavier
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - equipos
      - torneos
      - partidos
